project:
  type: website
  output-dir: _site

website:
  title: "Tricks in Econometricks"
  site-url: https://mostlyharmfuleconometrics.github.io/tricks-in-econometricks/
  repo-url: https://github.com/mostlyharmfuleconometrics/tricks-in-econometricks
  repo-actions: [source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Entries
  page-footer:
    center: "Tricks in Econometricks"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-fold: false
    code-copy: true
    html-math-method: katex

execute:
  echo: true
  warning: false
  message: false
